[build]
  base = "client"
  command = "npm run build"
  publish = "build"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = true

[build.environment]
  CI = "false"
  NODE_VERSION = "18"
  REACT_APP_API_URL = "https://your-backend-url.com"
